### ISSUE TITLE
Reconsider "prime_association" parameter name

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#100]
https://github.com/buddypress/BP-REST/blob/258f6cafba1186cece0cc29db16f30374f5f6ce3/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L750

The 'prime_association' parameter goes back to the original introduction of the Activity (and Messages?) endpoints. I assume it was introduced to come up with a general term that was less opaque than `item_id`. I think it's fine to introduce a new param name, but `prime_association`, in my view, obscures the fact that this parameter must be the integer ID for another WP/BP object. If we want something that's both clearer to the client developer and also consistent with BP internally, I'd suggest `primary_item_id` and `secondary_item_id`. Would welcome thoughts from others, though.

**Comment by renatonascalves** [comment]
Know that I'm probably wrong here, but as far as I know, this "pattern" is not clear on BuddyPress about the usage of `prime_association` and `primary_item_id`. It seems some components use one instead of the other.

Regardless, the `primary_item_id` seems to be more consistent throughout the components. PR #105 updates code to use it.

**Comment by boonebgorges** [comment]
You are correct that it's inconsistent in BP, but let's not make it any worse :)
