### ISSUE TITLE
Problem in viewing the activity

### ISSUE THREAD

**Issue by megin1989** [buddypress/BP-REST#120]
When i use the API "/buddypress/v1/activity/8693", i got the error.
"{"code":"rest_user_cannot_view_activity","message":"Sorry, you cannot view the activities.","data":{"status":401}}".
How can i solve the issue?. Please guide me.

**Comment by renatonascalves** [comment]
@megin1989 This is hard to say because I don't have enough context to confirm the reason. 

What I can say is that the user trying to see the activity doesn't have the necessary rights to see it. That might be because the activity is hidden, it is from a private or hidden group. The user might be banned, etc.

You kind of have to investigate.
