### ISSUE TITLE
Settings Endpoints

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#151]
Todo: add component endpoints and their verbs/endpoints.

**Comment by renatonascalves** [comment]
Closing this as it is not that revelant. :)

**Comment by imath** [comment]
Mmm, I thought this ticket was about the Settings component, the place where users can edit their emails, profile field visibility preferences, email alert preferences. Is there a ticket for this?

**Comment by renatonascalves** [comment]
It was not previously but we can make it so. Didn't think about that component.

Could you outline the main endpoints necessary for this component?

**Comment by imath** [comment]
I think the Email notification preferences would be the only one :)

**Comment by imath** [comment]
Well, after looking at it more closely.

I've changed my mind. I believe we don't need to create a controller for this component. Because:
- resetting the password / email etc.. should be already possible from the WordPress Users REST controller.
- Profile fields visibilities should be editable in the xProfile REST controller. 
- The email notices are (wrongly imho) depending on the Notification's component and we lack a real API. I doubt `bp_settings_get_registered_notification_keys()` would be fully usable.

Feel free to close the issue @renatonascalves.

**Comment by renatonascalves** [comment]
Tks! Closing!
