### ISSUE TITLE
Cannot remove group types via update endpoint

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#320]
When updating a group via the `groups/<id>` endpoint, the `types` parameter accepts a comma separated string.

If an empty string is provided, group types are unchanged.
If a non-empty string is provided, group types are appended.

There is no way to remove group types.

```
if ( isset( $prepared_group->group_id ) && isset( $request['types'] ) ) {

    // Append on update. Add on creation.
    $append = WP_REST_Server::EDITABLE === $request->get_method();

    // Add/Append group type(s).
    bp_groups_set_group_type( $prepared_group->group_id, $request['types'], $append );
}
```

Is there a reason why this is coded this way, or a different way to remove the types?

**Comment by renatonascalves** [comment]
This is likely a bug. Will take a look.

**Comment by renatonascalves** [comment]
After thinking for a bit about it. This one is a bit tricky since one might have a few possible scenarios to handle/update.

The current implementation takes into account new groups and their group types. To account for group type deletion, using the BuddyPress core function, `bp_groups_remove_group_type`, sending a group type would be required. But that would only delete on specific group type, not all at once.

To update a group removing all group types, sending an empty string might not be desired. Since one could forget or not know and delete its group types.

There is also the scenario where you might want to delete only one group type instead of all of them.

So @imath and @sjregan I don't have strong opinions about how that should be work. I'm happy to hear your suggestions.

**Comment by sjregan** [comment]
@renatonascalves My personal opinion (for what it's worth) is that API's should not try and protect against incorrect use. They need to be very specific about what they do. If you don't use an API according to it's specification you can't be surprised about the outcome.

The rabbit hole quickly becomes deep when you try and code around what people might expect to happen vs what the API parameter is for.

So in my mind if you specify a value for a parameter, you should expect the API to act on that parameter, and you should know what adding that parameter to your request does.

With this in mind, in the same way that the `description` field sets the description (it doesn't append to the existing description) I suggest the `types` field sets the BP types (and removes types not specified):

`bp_groups_set_group_type( $prepared_group->group_id, $request['types'], false );`

To allow users to append new types I suggest a new field `append_types` that is only available for PUT methods (or POST as well if that is meant to be supported) that would do:

`bp_groups_set_group_type( $prepared_group->group_id, $request['append_types'], true );`

**Comment by renatonascalves** [comment]
@sjregan Tks for your feedback! The PR above takes care of that.

**Comment by sjregan** [comment]
@renatonascalves lovely, looks good thanks.
