### ISSUE TITLE
Set last_activity on activity updates?

### ISSUE THREAD

**Issue by geckse** [buddypress/BP-REST#342]
I stumpled over a small issue when using only the BP Rest API. The _last_activity_ in the user_meta is never set, when no theme / frontend is used. In my case, I developed an app working with the REST-API, so there was never the need of a frontend / theme and I use Wordpress/Buddypress only as API. Which works great with this plugin, btw! 👍

But one small issue occurred in the Members endpoint. And the actual problem is more or less a Buddypress thing, I guess?
When calling the BP_User_Query class some of the arguments (type, eq.) require the user_meta "_last_activity_" to actual display the users. But when it's not set, the user probably never appeared in the members endpoint. 

I solved it with some action hooks, but maybe this might be an improvement for this plugin? Or at least some warning for ppl like me planing to use BP with this Plugin as API-Only.

**Comment by renatonascalves** [comment]
Interesting! That's actually a bug here. 

BuddyPress core updates this information every 5 minutes hooking into `wp_head` which it doesn't fire when using the BP REST API.

Could you share how you solved this just for comparison with how I'm thinking?

**Comment by geckse** [comment]
Not sure if it's the best way to implement it, tho.
Currently it hooks only on the REST functions.

Set last activity for current user on an actual activity update:
```php 
/*
  Track last activity on Activity Update of current user
  (via REST)
*/
add_action('bp_rest_activity_create_item','bp_rest_track_last_activity',10,3);
function bp_rest_track_last_activity($activity, $response, $request){
  $currentUserId = get_current_user_id();
  if($currentUserId == $activity->user_id){
    update_user_meta($currentUserId,'last_activity',date('Y-m-d H:i:s'));
  }
}
```

Set last activity for current user when he fetches his own profile (via members/me).
Which, in my case, happens every time the user reopens the app.
```php
/*
  Track last activity when user accesses own profile with "members/me"
  (via REST)
*/
add_filter('bp_rest_members_prepare_value', 'bp_rest_track_last_activity_on_memer_request',10,3);
function bp_rest_track_last_activity_on_memer_request($response, $request, $user){
  $currentUserId = get_current_user_id();
  $route = $request->get_route();
  if(strpos($route,'members/me') !== false && $currentUserId == $user->ID){
    update_user_meta($currentUserId,'last_activity',date('Y-m-d H:i:s'));
  }
  return $response;
}
```

**Comment by boonebgorges** [comment]
We discussed this in the BP dev chat this week.

First, be sure to use `bp_update_user_last_activity()` rather than `update_user_meta()`. BP's `last_activity` data is stored primarily in the activity tables, and only in usermeta for legacy reasons. `bp_update_user_last_activity()` handles this for you.

Second, there was general agreement that BP-REST itself should be doing something like @geckse 's first suggestion. That is, when a user creates an activity item, their `last_activity` should be bumped.

Third, as for bumping `last_activity` when a user accesses `/members/me`: This is a pretty good idea, as it's roughly analogous to the `wp_head` check that BP already does. I'd be in favor of adding this to BP-REST as well.

Fourth: Many clients won't access `members/me` on a regular basis, which means that client apps will need to ensure that `last_activity` is set using whatever mechanism makes sense for them. At a minimum, the client app might want to set the user's last activity at the time of account creation. In your case @geckse , since you access `members/me` regularly, then no further action would be needed for your app, as long as BP-REST bumps `last_activity` in this case.

@renatonascalves Does this analysis sound right to you?

**Comment by renatonascalves** [comment]
The analysis sounds ok to me! Will work on a PR with the suggested changes. :)
