### ISSUE TITLE
Cannot get activities from private groups

### ISSUE THREAD

**Issue by scottopolis** [buddypress/BP-REST#353]
Hey guys, I am trying to get activities for a private group (while authenticated) and it's not working. I saw [this comment](https://github.com/buddypress/BP-REST/issues/314#issuecomment-628360844) so I am wondering if that's intentional?

I am use a JWT bearer token for auth, and everything works including posting to a private group, but when I try to get activities it's empty. I know the activities are there because I can see them in the admin, and I know my group ID and authentication are correct. I am able to see public group activities just fine.

I am making a GET request to wp-json/buddypress/v1/activity?group_id=1 with a JWT bearer token, and it returns an empty array.

How do I get activities for a private group?

**Comment by renatonascalves** [comment]
@scottopolis  The "issue" might be the implied thinking that only a `group_id` is enough to get activities from a group. We need to confirm that a user has access to the private groups activites, the one doing that is the `show_hidden` method. Since the `component` args is not being sent with the request, it is assuming you don't have access to that private groups activity.

Quick solution to your issue will be adding the component `wp-json/buddypress/v1/activity?group_id=1&component=groups` to the request.

Long-term solution might be handling that ourselves in the implementation. @imath what do you think?

**Comment by imath** [comment]
Here's what I think, the component argument should only be necessary if the request would look like this:
`wp-json/buddypress/v1/activity?item_id=1&component=custom` if it looks like this `wp-json/buddypress/v1/activity?group_id=1` then we should set the component to `groups` ourselves otherwise it can be challenging to understand why we need to set the component argument if I've sent a group id?

**Comment by renatonascalves** [comment]
By `item_id`, I think you mean `primary_id`?

But that's right! Going to send a PR with a suggestion. :)

**Comment by scottopolis** [comment]
Thanks you guys!
