### ISSUE TITLE
Update Extending Docs

### ISSUE THREAD

**Issue by dominic-ks** [buddypress/BP-REST#368]
Hello,

Is there a reason that the page on extending endpoints seems to suggest extending endpoints is limited? This line:

"_You can extend the Activity, Member, Group, Messages, Notifications, xProfile group, xProfile Field and xProfile data endpoint responses registering custom REST fields using the bp_rest_register_field() function._"

Which is here -[https://developer.buddypress.org/bp-rest-api/extending-the-bp-rest-api/]( https://developer.buddypress.org/bp-rest-api/extending-the-bp-rest-api/)

When, it seems it's totally possible to add fields to, for example, the `/friends` endpoint?

**Comment by renatonascalves** [comment]
I think when that content was created, the friends endpoint wasn't built yet.

**Comment by dominic-ks** [comment]
OK thanks, is it possible to contribute to the docs? Happy to update them myself.

**Comment by renatonascalves** [comment]
As far as I know, it is not possible right now! I'm going to ping @imath he is the one who has been updating that since the beginning. :)

**Comment by imath** [comment]
@dominic-ks you can write your changes in a comment to this issue, I’ll take care and of updating the documentation, thanks in advance for your help 😍

imath
https://imathi.eu
________________________________
De : Renato Alves <notifications@github.com>
Envoyé : Monday, December 28, 2020 3:08:21 PM
À : buddypress/BP-REST <BP-REST@noreply.github.com>
Cc : imath <imathi.eu@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [buddypress/BP-REST] Update Extending Docs (#368)


As far as I know, it is not possible right now! I'm going to ping @imath<https://github.com/imath> he is the one who has been updating that since the beginning. :)

**Comment by dominic-ks** [comment]
@imath Hello, I think for a quick change for this you could probably just replace this paragraph:

"_You can extend the Activity, Member, Group, Messages, Notifications, xProfile group, xProfile Field and xProfile data endpoint responses registering custom REST fields using the bp_rest_register_field() function._"

With:

"_You can extend any of the data endpoint responses by registering custom REST fields using the bp_rest_register_field() function._"

The current examples that follow are generic using _activity_ as an example, I think just so it doesn't appear to limit this functionality to certain endpoints when it works for all.

Cheers!

**Comment by imath** [comment]
Thanks a lot @dominic-ks It's updated: https://developer.buddypress.org/bp-rest-api/extending-the-bp-rest-api/

**Comment by dominic-ks** [comment]
Great cheers.
