### ISSUE TITLE
Create activity with image attached

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#443]
Hi, first thank you for this amazing API 

 can you please guide me what's the endpoint  for creating activity with an image 
I mean post a text with an image OR post just an image

Thanks

![iScreen Shoter - 2022-04-27 01:54:43 837](https://user-images.githubusercontent.com/80561800/165451383-c6437a71-cb51-4981-8aa5-45055ba773c1.jpg)

**Comment by renatonascalves** [comment]
This is tricky because one can save an activity image in multiple ways in BuddyPress. As far as I know, there is no standard way to save an image together with the activity, hence why the endpoint doesn't have a clear way to do that. The answer to your question will depend on how your app will save and use that information. 

However, it is possible to use the activity endpoint to append an image URL so that you can properly upload it in the back using this hook: https://github.com/buddypress/BP-REST/blob/df5ddbc53dd772ea02cb8cb7af982b2e26665852/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L967

Endpoint: https://developer.buddypress.org/bp-rest-api/reference/activity/#create-an-activity

The main point I'd like to share is: activity image upload is something custom that you will need to handle yourself. There is simply no way we can account for all use cases. Some apps might save the image together with the content, others might save in the activity meta table.

**Comment by imath** [comment]
I confirm we don't support yet this feature in BuddyPress but this is something we're targeting into the BP Attachments plugin. What I would do in the meantime would be to use the WordPress attachment endpoint first, get the image url and add it into the activity content. Thanks a lot @renatonascalves for your detailed explanation 👍
