### ISSUE TITLE
Activity - create_item and get_items return different data

### ISSUE THREAD

**Issue by modemlooper** [buddypress/BP-REST#477]
Came across an issue where there is no way to hook into activity creation and then filter the activity item prepare value because the only hook is after the api gets the activity item.

The create and get items should return the exact same thing and that is not happening because the get_items function has filters / actions and the create _item does not. Probably should have a bp_rest_get_activity function with filters / hooks that both the create and get item function can use and then return the same data.

Mainly talking about here: https://github.com/buddypress/BP-REST/blob/master/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L420

The item is added but there isn't a simplified way to hook into this add functionality before the bp_get_activity returns the data without being able to filter or add an action. 

there is a hook after the returned data: "bp_rest_activity_create_item" which is kinda false because its not after creating its after the data is being returned.

**Comment by renatonascalves** [comment]
> Came across an issue where there is no way to hook into activity creation and then filter the activity item prepare value because the only hook is after the api gets the activity item.

If I understood this phrase correctly, you are looking for the `bp_rest_activity_pre_insert_value` filter hook.

--

We have two hooks that can modify values before being created/updated (prepare value) and on GET requests.

Essentially, they are mapped to the `prepare_item_for_database`, and the `prepare_item_for_response` methods. As far as I remember (I'd need to check all the endpoints), there is no filter hook after the item is created/updated/got.

There is an action hook so that plugin authors can perform actions but not modify the returned value.

--

> The create and get items should return the exact same thing and that is not happening because the get_items function has filters / actions and the create _item does not

I don't know what you meant here but I can assure you there is no filter hook for the `get_items`. All the items are passed through `bp_rest_activity_prepare_value`. Plugin authors should hook there to add any new fields.

**Comment by renatonascalves** [comment]
@modemlooper 

As I mentioned, this is the hook where you can update the object **before** creation/update:

https://github.com/buddypress/BP-REST/blob/375265f931dcf3bc428b78ff05be3bde75063450/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L1097

This is the one to hook into **before returning the object to the user**:

https://github.com/buddypress/BP-REST/blob/375265f931dcf3bc428b78ff05be3bde75063450/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L964

There is no hook between those tasks in any of the endpoints in the BP REST API. If you want to change this object here, https://github.com/buddypress/BP-REST/blob/375265f931dcf3bc428b78ff05be3bde75063450/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L420, you'd need to do inside `bp_activity_get`, in BuddyPress itself.

**Comment by renatonascalves** [comment]
The premise of the question though is that `create_item` and `get_items` should return the same data, but it is not. If you could share more about this, I'd appreciate it. In case it is a bug or normal behavior.

**Comment by modemlooper** [comment]
There should be a hook right before bp_acivity_get because nowhere in that function it specifies its the rest api. In the get_items function its the hooks are explicit that it is th rest api.

**Comment by modemlooper** [comment]
Example: https://github.com/modemlooper/BP-REST-1/blob/master/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L361

**Comment by renatonascalves** [comment]
@modemlooper Could you elaborate on what you are trying to do? What are you trying to modify and how? I'm sorry but I'm really not getting what you are doing that the current hooks can't do.

**Comment by modemlooper** [comment]
If you include extra data in the POST request to create_item and you want to use that data to process that data in relation to the activity item created you can not do this because the only hook is `bp_rest_activity_pre_insert_value ` and then the next hook is in bp_activity_get but you can use the request object here and then its too late and you have no access to the activity id to do anything with it.

**Comment by renatonascalves** [comment]
> If you include extra data in the POST request to create_item 

What sort of extra data? To do what exactly?

**Comment by modemlooper** [comment]
I came across this issue when sending files data along with POST. You can send the data and even process the files but the response does not include what is being filtered during the hook `bp_rest_activity_prepare_value`. This is because the only hook you can use with the activity id is after bp_activity_get. There needs to be a hook right before this where it passes the activity id and rest request object

So, in this case the images get processed upload, formatted by wp and I filter the activity  `bp_rest_activity_prepare_value` to include these in the response but during create_item the images are blank in the response because bp_activity_get is before the hook and returns the data without the filter.

Yes, there are hooks before as you have mentioned but they either don't include the activity id or the rest request object

**Comment by renatonascalves** [comment]
I think I'm quite getting it. Could I see a snippet of the request? So that I can try to replicate what you are doing.

**Comment by modemlooper** [comment]
Well, I did get it to work but it runs the code twice because of the way the hooks in the api are set up. This is not ideal. Basically had to add the same code I have in prepare_value to create_item hook because it runs after bp_activity_get and the prepare value runs in the middle but like I said before those hooks don't include the rest request data to process it.

So currently to get it to work is to run the prepare value hook to get the images which will be blank because they haven't even been processed then override the blank attachments array in the create_item hook.

`/**
 * Filter notification response returned from the API. Creates and includes attachments.
 *
 * @since 1.0.0
 *
 * @param WP_REST_Response              $response     The response data.
 * @param WP_REST_Request               $request      Request used to generate the response.
 * @param BP_Notifications_Notification $notification Notification object.
 *
 * @return WP_REST_Response
 */
function appp_add_attachments_to_activity_items( $activity, $response, $request ) {

	$files = $request->get_file_params();

	if ( isset( $files['files'] ) ) {
		appp_upload_attachment_from_file( $files['files'], $activity->id );

		$attachments                      = appp_get_activity_attachments( $activity->id );
		$response->data[0]['attachments'] = apply_filters( 'bp_rest_activity_create_item_attachments', $attachments, $activity );
	}

	return $response;

}
add_action( 'bp_rest_activity_create_item', 'appp_add_attachments_to_activity_items', 10, 3 );
`

**Comment by renatonascalves** [comment]
Are you saying you can't access the `$request` with the images/files via the `bp_rest_activity_prepare_value`?

**Comment by renatonascalves** [comment]
Why that would not work?

```php

function appp_add_attachments_to_activity_items( $response, $request, $activity ) {
	$files = $request->get_file_params();

	if ( isset( $files['files'] ) ) {
		appp_upload_attachment_from_file( $files['files'], $activity->id );

		$attachments                      = appp_get_activity_attachments( $activity->id );
		$response->data[0]['attachments'] = apply_filters( 'bp_rest_activity_create_item_attachments', $attachments, $activity );
	}

	return $response;
}
add_filter( 'bp_rest_activity_prepare_value', 'appp_add_attachments_to_activity_items', 10, 3 );
```

**Comment by modemlooper** [comment]
bp_rest_activity_prepare_value runs during the get_items function and I don't think its a good idea to hook here when its not exactly what is happening. The uploading of happens during POST not GET

**Comment by renatonascalves** [comment]
> bp_rest_activity_prepare_value runs during the get_items function...

That's incorrect. The `bp_rest_activity_prepare_value` hook runs for `POST/PUT/GET/DELETE`. You have access to the `$request` object and can skip other actions if necessary.

**Comment by renatonascalves** [comment]
Just to be more transparent, I'm not opposed to introducing a new filter hook in the `create_item` before the `bp_rest_activity_prepare_value` hook, I'm just not seeing the need for one.

**Comment by modemlooper** [comment]
My point was you will introduce code for every single activity item returned if you hook to bp_rest_activity_prepare_value regardless if your only intention was to run code once during a POST request.

No worries if you don't want to add something, good thing WP and BP is open and I can just write my own API. I just brought this up because bp_rest_activity_prepare_value is  not the correct place to be processing files.

**Comment by renatonascalves** [comment]
> My point was you will introduce code for every single activity item returned if you hook to bp_rest_activity_prepare_value regardless if your only intention was to run code once during a POST request.

Since one has access to the `$request` object, one can easily target the filter hook to a `POST` request only. You would not need to run for every single activity item.

I'd love @imath's take here as well. I don't personally see the need. I'm not seeing a good reason for another, new, filter hook only for processing those files.

**Comment by imath** [comment]
Hi @renatonascalves & @modemlooper 

Interesting discussion. I think I didn't have this need for the BP Attachments plugin because I was using the BP Activity Block Editor. In short, the attachment is uploaded before the activity is created then added as content inside the activity using the WP Block parsed code. Once published I do parse the activity content to find the Attachment ID and then do the linking between both objects.

Problem I can see in the current code is we return an error early if we don't have a content. It can be problematic if you're only using an attachment.

That being said, 2 hooks before and after is probably not the best design I agree with @renatonascalves there.

Here's what I'd do: I'd copy the `create_item()` logic of the [WordPress post endpoint](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php) Run prepare for database early making sure it includes a filter before returning the prepared activity (I believe it exists, but haven't checked). That should leave the space to plugin authors to extend the activity object before it has been created, and then use the hook fired once created to do the Attachment / Activity linking if needed.

**Comment by renatonascalves** [comment]
I wonder why one would upload an activity attachment before the activity was even created. 🤔 

Taking aside any technical reason, is that a good way to approach it?

A few years ago, I built a feature just like that, uploading an activity attachment to [AppPresser](https://apppresser.com/) without needing two hooks.
